name: epub
version: 2.1.0
author: Colin Nelson <colin@orthros.dev>
description: Epub Parser for Dart. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  async: ">=1.8.0 <3.0.0"
  archive: "^2.0.0"
  quiver: ">=2.0.0 <3.0.0"
  xml: ">=2.6.0 <4.0.0"
  image: ">=1.1.33 <3.0.0"
  dart2_constant: ^1.0.1
dev_dependencies:
  test: "^1.0.0"
  path: "^1.5.1"
  pedantic: "^1.8.0"
